### ISSUE TITLE
Question about contractor work

### ISSUE THREAD

**Issue by NoahKunin** [unitedstates/licensing#11]
You currently recommend stating when a work has been done by a "government contract" but still transferred to the Government agency.

> This work was created through a government contract which assigned copyright to [the United States Government or Agency name]. [Agency Name] waives copyright and related rights in the work worldwide through the CC0 1.0 Universal Public Domain Dedication (which can be found at http://creativecommons.org/publicdomain/zero/1.0/).

Curious as to the thought process for this one. If it was created _through_ a government contract, and therefore via the period of performance of contractors, and is thus a new work, why should I posit that copyright was waived? They never had it to begin with in that scenario, presuming the contract was written to FAR spec.

**Comment by JoshData** [comment]
They are hereby-waiving through the application of CC0 here. Right?

**Comment by konklone** [comment]
The US government can have copyright assigned to it by non-governmental actors who authored copyrightable works, so I think this was written with that in mind.

**Comment by NoahKunin** [comment]
Gotchya - I think we're talking about two different things here. 

You state "Works _produced_ under a contract with the government may be subject to copyright protection". If you've written the contract to spec correctly, that's not true. [FAR 27.404-1](http://www.acquisition.gov/far/html/Subpart%2027_4.html#wp1041836) states that the Government already has "unlimited rights" to all data "produced in the performance of a contract". 

Data is defined very broadly by the FAR - its scope is all "recorded information". [FAR 52-227-1](http://www.acquisition.gov/far/html/52_227.html#wp1139363) states "prior, express written permission of the Contracting Officer is required to assert copyright" _in all data_ produced via the contract. 

That's why as a Contracting Officer, I got confused reading this section. If my contractor assigned the Government a copyright for works produced under the contract, that means that I gave them permission to do so, even though my final intent was to release it under a public domain license anyway. Giving contractors copyright under a contract is extremely rare to begin with, so the only time I would use this part of the boilerplate as written is a situation in which I did not intend to release the work or data, gave permission to the contractor to obtain copyright, then I changed my mind, and somehow convinced the contractor to release their copyright through CC0. Which, given the request to get a copyright to begin with, wouldn't make sense for their interests.

So, it seems like a pretty extreme edge case. Makes sense to me to simplify here, as the other boilerplate can be used just fine in this situation as well. For work produced in part or in whole by a contractor, the main use case we encounter is when the deliverable is mixed - in part produced under the contractor (no problem) in part a result of work produced _outside_ the contract, usually under awkward or grey copyright. I think this section should focus on that problem, something I can help you on.

**Want to be clear that I'm overall thrilled with the work ya'll are doing.** But as an actual member of the Contracting Officer community (the audience), this section threw me for a complete loop.

*If you read the FAR, you'll see that contractors get a copyright carve out for submissions to academic or scientific journals, but only to the articles themselves, not the underlying data. My understanding is that it's there to encourage information sharing, etc.

**Comment by JoshData** [comment]
Hey. Really appreciate your taking the time to work through this thoroughly.

In FAR 27.404-1: "The Government acquires unlimited rights". What I think this means is that the government acquires the copyright, and so has the right to assert copyright itself. Let's put the details of that aside though. The most important thing we're getting at is that this situation is probably not covered by 17 USC § 105, which is the exemption of U.S. government works from copyright. Another way to say it would be that as opposed to USG works which are born into the U.S. public domain, works produced under FAR 27.404-1 are born copyrighted. I wish I had better references, but it's mostly based on the Copyright Office's guidance: http://www.copyrightcompendium.com/#206.02

**Comment by NoahKunin** [comment]
Forgot to close this one out! Mea culpa

@JoshData: Totally get you now. For me I guess it was kneejerk reaction that copyright was even created in the first place. In my mind the work is created with unlimited rights/potential at which point the Government decides to place it into the public domain. This is a _very_ nuanced difference, so I'm not too concerned, but you never know what legal loopholes are used later in life.

So if there was any edit, it would read:

> This work was created through a government contract which assigned **unlimited rights** to [the United States Government or Agency name]. [Agency Name] waives **all rights** in the work worldwide through the CC0 1.0 Universal Public Domain Dedication (which can be found at http://creativecommons.org/publicdomain/zero/1.0/).

**Comment by JoshData** [comment]
Actually I'm gonna re-open this! This "unlimited rights" thing is something we should address.

**Comment by konklone** [comment]
Yeah - @NoahKunin, anyone you want to CC in to this thread, and/or any way you'd like to make this become a PR for the `v3` branch?

**Comment by NoahKunin** [comment]
Aw, thanks for the issue phoenix down! ![phoenixdown copy 2](https://f.cloud.github.com/assets/565071/2303183/ab4f01be-a1a5-11e3-81f2-9b612a9c01ae.gif)

I'm told there may be some gov lawyers who can weigh in on this...@eriemeyer? I've sort of tapped out the majority of my lists to potentially CC into this. I can hit up my people again and see if anything has changed.

**Comment by NoahKunin** [comment]
@eriemeyer has made a connection with OSTP re: this issue. Processing now, update soon.

**Comment by NoahKunin** [comment]
I think this can be re-closed - not sure what else there is to say that hasn't been addressed. 

That being said, this has been tremendous work that has moved the conversation along considerably. IMHO, it's time to go for the brass ring. 

I want a license / waiver that works for _all works_, regardless of medium.
