### ISSUE TITLE
License for this document itself

### ISSUE THREAD

**Issue by konklone** [unitedstates/licensing#18]
Ironically, we never chose a license for this document itself.

I'm strongly in favor of CC0, given the contents of the document. Whichever license we choose, I'll add a `CONTRIBUTING.md` file that says future contributions will be accepted under that license going forward.

Right now, it's all copyrighted by default by everyone involved, so I'll need to get a :+1: from the contributors so far. That's:
- [x] @punkish
- [x] @tvol
- [x] @jwyg
- [x] @konklone
- [x] @JoshData 
- [x] @thisisparker 
- [x] @mwweinberg 
- [x] @rebeccawilliams

@JoshData, let me know if I'm missing anyone.

If CC0 is OK with you, give a :+1: in the comments. Or, you can object and we can talk it out.

**Comment by rebeccawilliams** [comment]
:+1: :accept:

**Comment by punkish** [comment]
CC0 (puneet)

**Comment by JoshData** [comment]
:+1:

There may have been others from the sign-on process. Will have to check my mail archive.

**Comment by tvol** [comment]
:+1:

**Comment by thisisparker** [comment]
+1

On Mon, Mar 17, 2014 at 4:21 PM, Timothy Vollmer
notifications@github.comwrote:

> +1
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/unitedstates/licensing/issues/18#issuecomment-37883251
> .

## 

parker higgins
san francisco, ca

http://parkerhiggins.net

gmail / gchat: parkerhiggins@gmail.com
twitter / identi.ca: @xor

please consider software freedom before reading this e-mail on a
proprietary platform

**Comment by mwweinberg** [comment]
+1

**Comment by jwyg** [comment]
:+1: :-)

**Comment by konklone** [comment]
This is done in https://github.com/unitedstates/licensing/commit/4cad5ee3a77cb5e372adb63526c6a336eb5a68d7, thanks everyone!
