### ISSUE TITLE
please list Creative Commons as supporter

### ISSUE THREAD

**Issue by tvol** [unitedstates/licensing#19]
Creative Commons supports this and if possible would like to be added under the "Supporters" heading (linking to https://creativecommons.org/). Apologies for the lame tardiness on our part.

**Comment by konklone** [comment]
Thank you @tvol, that's terrific! I've added Creative Commons, near the top of the supporters list (since you/CC were original helpers on v1).

:us: :us: :us:

**Comment by JoshData** [comment]
@tvol : Would you want to come in now as an author?

**Comment by tvol** [comment]
@JoshData sure, although I don't think i helped much with the original drafting. but i'm happy to help more now, especially if there are any future updates.

**Comment by JoshData** [comment]
Done in 964d32c035b27b932b823ad6b1b9116399200c55.
