### ISSUE TITLE
What's the best citation to show that US public domain legally ends on our shores?

### ISSUE THREAD

**Issue by NoahKunin** [unitedstates/licensing#20]
I know http://www.usa.gov/copyright.shtml exists, but that's a little weak. If I recall, it had something either to do with the courts, or the discussion in Congress at the time....

**Comment by tvol** [comment]
I think you might be referring to text in the legislative report, which accompanies the 1976 Copyright Act: 

https://en.wikisource.org/wiki/Page:H.R._Rep._No._94-1476_(1976)_Page_059.djvu

"The prohibition on copyright protection for United States Government works is not intended to have any effect on protection of these works abroad. Works of the governments of most other countries are copyrighted. There are no valid policy reasons for denying such protection to United States Government works in foreign countries, or for precluding the Government from making licenses for the use of its works abroad."

**Comment by NoahKunin** [comment]
Yes! Exactly. Been bugging me all day. Major kudos @tvol.
