### ISSUE TITLE
More uses of our rec in govt

### ISSUE THREAD

**Issue by JoshData** [unitedstates/licensing#22]
Things we could cite in future updates-

http://www.whitehouse.gov/sites/default/files/microsites/ostp/us_open_data_action_plan.pdf
(see bottom of page 2)

**Comment by konklone** [comment]
I'm not opposed to updating the doc in-place with a link.

**Comment by tvol** [comment]
@JoshData Very cool. And the report cites several examples of CC0 already being used for federal datasets. Perhaps the U.S. federal government is really turning a corner on this!

**Comment by konklone** [comment]
I updated HISTORY.md in https://github.com/unitedstates/licensing/commit/0763a315afa0b6091e4d27029a528ae33f9ab33d to mention it, along with CC's joining last month.
