### ISSUE TITLE
Add a TLDR;-style short version to the top of the document

### ISSUE THREAD

**Issue by konklone** [unitedstates/licensing#28]
I think the document could get to the point about "Just use CC0" sooner, or make it louder for those landing on the site and just wanting to get het gist. 

Instead of adjusting the language, how about a brief TLDR;-style header at the top, maybe:

> **The short version**: All US government data should be part of the international public domain, no matter how it's created. Use a dedication like [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) to accomplish this.

Assuming I've summed it up correctly, I don't think this would be a substantive change that would merit getting re-signoff from all the signers.

**Comment by JoshData** [comment]
I think a little less normative would be fine.

>  To the greatest extent possible U.S. public government data should be “license-free”. Here's how to use the [Creative Commons CC0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/legalcode) to make data license-free.

**Comment by konklone** [comment]
:+1: Yeah, I like that. I'll give a day or two for others to ring in.

**Comment by tvol** [comment]
:+1:
