### ISSUE TITLE
Update document to mention 18F and DCGov?

### ISSUE THREAD

**Issue by konklone** [unitedstates/licensing#36]
Both 18F and the DC government have adopted forms of our initial proposal here:
- https://github.com/18F/open-source-policy/blob/master/LICENSE.md
- https://github.com/DCgov/license/blob/master/LICENSE.md

Should the main document be updated to augment the little example link boxes with link to 18F and DC, alongside the existing WH and CFPB links?

**Comment by JoshData** [comment]
I wonder if we should use a new style/boxes so we can indicate that they were not a part of the original doc?

**Comment by konklone** [comment]
Hmm - is it worth doing a v3? Anything else we'd change?

**Comment by JoshData** [comment]
I think the doc has done its job. I don't have any major thoughts on changes.

**Comment by konklone** [comment]
@JoshData What if we used language inside the box to indicate "Since original publication, ..."?

**Comment by JoshData** [comment]
Yes yes. Sorry I was just responding to whether there was anything else to change. +1 to a box that  indicates it wasn't part of the original.

**Comment by JoshData** [comment]
also + https://github.com/uscensusbureau/open-source-policy

**Comment by konklone** [comment]
We had 18F in there already - I'm adding DC and Census now.
